using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace DMM.Pages
{
    public partial class AnalysisPage : DevExpress.XtraEditors.XtraUserControl
    {
        DBDMMEntities db;

        public AnalysisPage()
        {
            InitializeComponent();
            SupplierGetData();
            CustomerGetData();
            TotalDebitGetData();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DMM.DBDMMEntities dbContext = new DMM.DBDMMEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Debit_Customers.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    chartControl1.DataSource = dbContext.Debit_Customers.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void SupplierGetData()
        {
            try
            {
                db = new DBDMMEntities();

                var Data = (double)db.TB_Suppliers.Select(x => x.Debit).ToArray().Sum();
                txt_Supplier.Text = Data.ToString();

            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void CustomerGetData()
        {
            try
            {
                db = new DBDMMEntities();

                var Data = (double)db.TB_Customers.Select(x => x.Debit).ToArray().Sum();
                txt_Customer.Text = Data.ToString();

            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        private void TotalDebitGetData()
        {
            try
            {
                db = new DBDMMEntities();

                var Data1 = (double)db.TB_Customers.Select(x => x.Debit).ToArray().Sum();
                var Data2 = (double)db.TB_Suppliers.Select(x => x.Debit).ToArray().Sum();
                txt_totalDebit.Text = (Data1+Data2).ToString();

            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }
    }
}
